### ISSUE TITLE
Error when launching 

### ISSUE THREAD

**Issue by hellopathere** [RivaanRanawat/cuadro#2]
Hi,
I get this error when running. When updating cocoapods nothing changes. 

<img width="1387" alt="Screen Shot 2021-09-28 at 12 29 23 PM" src="https://user-images.githubusercontent.com/83986056/135128096-f9983d24-1781-4dbd-a236-7f027884966d.png">

**Comment by RivaanRanawat** [comment]
Try going to the root of your project and running:
`pod install`

If cocoapods are not installed run:
`sudo gem install cocoapods`

and then again run
`pod install`

Hope this helps you!
